site_name: kn-sock Documentation
site_description: Comprehensive documentation for kn-sock - A simplified socket programming toolkit for Python with TCP/UDP, WebSockets, RPC, Pub/Sub, and more
site_author: KhagendraN
site_url: https://khagendran.github.io/kn-sock/

repo_name: KhagendraN/kn-sock
repo_url: https://github.com/KhagendraN/kn-sock
edit_uri: edit/main/docs/

theme:
  name: material
  logo: kn-sock_logo.png
  favicon: kn-sock_logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KhagendraN/kn-sock
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/kn-sock/

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Docker Setup: docker.md
  - Configuration: configuration.md
  - Protocols:
    - TCP: protocols/tcp.md
    - UDP: protocols/udp.md
    - WebSocket: protocols/websocket.md
    - JSON: protocols/json.md
    - File Transfer: protocols/file-transfer.md
    - Secure TCP (SSL/TLS): protocols/secure-tcp.md
  - Advanced Features:
    - Pub/Sub Messaging: advanced/pubsub.md
    - Remote Procedure Calls: advanced/rpc.md  
    - Live Streaming: advanced/live-streaming.md
    - Video Chat: advanced/video-chat.md
    - HTTP/HTTPS: advanced/http.md
  - Network Visibility:
    - ARP Scanning: network/arp.md
    - MAC Address Lookup: network/maclookup.md
    - DNS Monitoring: network/monitor.md
  - Utilities:
    - Error Handling: utilities/error-handling.md
    - Compression: compression.md
    - Load Balancing: utilities/load-balancing.md
    - Message Queues: utilities/message-queues.md
    - Protocol Buffers: utilities/protobuf.md
    - Network Utilities: utilities/utilities.md
  - Reference & Guides:
    - API Reference: api-reference.md
    - Decorators: decorators.md
    - CLI Guide: cli.md
    - Examples: examples.md
    - Troubleshooting: troubleshooting.md
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
