name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30  # Increase job timeout (optional)
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update package list
        run: sudo apt-get update
        timeout-minutes: 2

      - name: Install system dependencies for PyAudio
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y portaudio19-dev
        timeout-minutes: 2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest codecov pytest-cov

      # Ensure dependencies are not reinstalled unless requirements.txt changes

      - name: Run tests with pytest
        run: pytest --cov=kn_sock --cov-report=xml
        timeout-minutes: 10

      - name: Upload coverage to Codecov
        if: github.secrets.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false

      - name: CI Finished
        run: echo "✅ CI workflow completed successfully."
